import { spawnSync } from 'node:child_process'
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, sep } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

import matter from 'gray-matter'

import { type ContentBundle, type ParsedContentSourceFile, createContentBundle } from '@tsl/shared'

const scriptDirectory = dirname(fileURLToPath(import.meta.url))
const repositoryRoot = join(scriptDirectory, '../../..')
const contentRoot = join(repositoryRoot, 'content')
const generatedContentPath = join(repositoryRoot, 'apps/web/src/lib/generated-content.ts')

function collectContentFiles(directory: string, sourceRoot = directory): ParsedContentSourceFile[] {
  return readdirSync(directory, { withFileTypes: true })
    .sort((a, b) => a.name.localeCompare(b.name, 'en'))
    .flatMap((entry) => {
      const entryPath = join(directory, entry.name)

      if (entry.isDirectory()) {
        return collectContentFiles(entryPath, sourceRoot)
      }
      if (!entry.isFile() || !entry.name.endsWith('.md')) {
        return []
      }

      const relativePath = relative(sourceRoot, entryPath).split(sep).join('/')
      try {
        const parsed = matter(readFileSync(entryPath, 'utf8'))
        return [{ relativePath, frontmatter: parsed.data, body: parsed.content }]
      } catch (error) {
        const detail = error instanceof Error ? error.message : 'failed to parse frontmatter'
        throw new Error(`${relativePath}: ${detail}`)
      }
    })
}

export function createGeneratedContentModule(bundle: ContentBundle): string {
  return `// Generated by apps/web/scripts/generate-content.ts. Do not edit manually.\nimport 'server-only'\nimport type { ContentBundle } from '@tsl/shared'\n\nexport const bundledContent = ${JSON.stringify(bundle, null, 2)} satisfies ContentBundle\n`
}

function formatGeneratedContentModule(source: string): string {
  const biomeBin = process.platform === 'win32' ? 'biome.cmd' : 'biome'
  const result = spawnSync(
    join(repositoryRoot, 'node_modules/.bin', biomeBin),
    ['format', '--stdin-file-path', generatedContentPath],
    { cwd: repositoryRoot, encoding: 'utf8', input: source },
  )

  if (result.status !== 0) {
    throw new Error(result.stderr || 'failed to format generated content')
  }

  return result.stdout
}

export function renderContentModule(): string {
  return formatGeneratedContentModule(
    createGeneratedContentModule(createContentBundle(collectContentFiles(contentRoot))),
  )
}

export function generateContentModule(): void {
  writeFileSync(generatedContentPath, renderContentModule(), 'utf8')
}

export function checkGeneratedContentModule(): void {
  const actual = readFileSync(generatedContentPath, 'utf8')
  const expected = renderContentModule()

  if (actual !== expected) {
    throw new Error('generated-content.ts is stale; run pnpm content:generate')
  }
}

const entryPath = process.argv[1]
if (entryPath && import.meta.url === pathToFileURL(entryPath).href) {
  if (process.argv.includes('--check')) {
    checkGeneratedContentModule()
  } else {
    generateContentModule()
  }
}
