import { spawnSync } from 'node:child_process'
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, sep } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

import matter from 'gray-matter'

import { type ContentBundle, type ParsedContentSourceFile, createContentBundle } from '@tsl/shared'

const scriptDirectory = dirname(fileURLToPath(import.meta.url))
const repositoryRoot = join(scriptDirectory, '../../..')
const contentRoot = join(repositoryRoot, 'content')
const generatedEstimatesPath = join(repositoryRoot, 'apps/api/src/content-estimates.ts')

function collectContentFiles(directory: string, sourceRoot = directory): ParsedContentSourceFile[] {
  return readdirSync(directory, { withFileTypes: true })
    .sort((a, b) => a.name.localeCompare(b.name, 'en'))
    .flatMap((entry) => {
      const entryPath = join(directory, entry.name)

      if (entry.isDirectory()) {
        return collectContentFiles(entryPath, sourceRoot)
      }
      if (!entry.isFile() || !entry.name.endsWith('.md')) {
        return []
      }

      const relativePath = relative(sourceRoot, entryPath).split(sep).join('/')
      try {
        const parsed = matter(readFileSync(entryPath, 'utf8'))
        return [{ relativePath, frontmatter: parsed.data, body: parsed.content }]
      } catch (error) {
        const detail = error instanceof Error ? error.message : 'failed to parse frontmatter'
        throw new Error(`${relativePath}: ${detail}`)
      }
    })
}

export function createGeneratedContentEstimatesModule(bundle: ContentBundle): string {
  const estimates = Object.fromEntries(
    [...bundle.lessons]
      .sort((left, right) => left.lessonId.localeCompare(right.lessonId, 'en'))
      .map((lesson) => [lesson.lessonId, lesson.estimatedMinutes]),
  )

  return `// Generated by apps/api/scripts/generate-content-estimates.ts. Do not edit manually.
export const estimatedMinutesByLesson = ${JSON.stringify(estimates, null, 2)} as const
`
}

function formatGeneratedContentEstimatesModule(source: string): string {
  const biomeBin = process.platform === 'win32' ? 'biome.cmd' : 'biome'
  const result = spawnSync(
    join(repositoryRoot, 'node_modules/.bin', biomeBin),
    ['format', '--stdin-file-path', generatedEstimatesPath],
    { cwd: repositoryRoot, encoding: 'utf8', input: source },
  )

  if (result.status !== 0) {
    throw new Error(result.stderr || 'failed to format generated content estimates')
  }

  return result.stdout
}

export function renderContentEstimatesModule(): string {
  const bundle = createContentBundle(collectContentFiles(contentRoot))
  return formatGeneratedContentEstimatesModule(createGeneratedContentEstimatesModule(bundle))
}

export function generateContentEstimatesModule(): void {
  writeFileSync(generatedEstimatesPath, renderContentEstimatesModule(), 'utf8')
}

export function checkGeneratedContentEstimatesModule(): void {
  const actual = readFileSync(generatedEstimatesPath, 'utf8')
  const expected = renderContentEstimatesModule()

  if (actual !== expected) {
    throw new Error('content-estimates.ts is stale; run pnpm content:generate')
  }
}

const entryPath = process.argv[1]
if (entryPath && import.meta.url === pathToFileURL(entryPath).href) {
  if (process.argv.includes('--check')) {
    checkGeneratedContentEstimatesModule()
  } else {
    generateContentEstimatesModule()
  }
}
